### ISSUE TITLE
How to simplify code examples from readme?

### ISSUE THREAD

**Issue by markfswe** [starbasehq/sveltekit-openid-connect#20]
Hi :) Thank you for this work <3

Came here from https://github.com/tushar10sh/sveltekit-oidc/issues/6#issuecomment-1832113542

I have tried to go through readme, started copying code but it seems too complicated to me. I have too little experience with authorization/authentication, and zero experience with Auth0, Keycloak, OpenID and JWT. Could you please help me understanding what's going on here? :D

I am building pretty simple frontend app using sveltekit (ssr) and some open-id realm which is being used in other services/apps. So the main question for me is why do I need DB? How this would be implemented on frontend without SSR? I don't really understand, how to simplify code examples from readme. I would like to use SSR and fullstack benefits, but no heavily rely on it. For me this is just looks scary because I don't know anything about DBs, how this could affect performance of my SSR app? Which db to choose? etc..

So the question is how can I drop DB from this setup and which features/abilities I'll loose? And maybe you'll understand me if you'll compare readme from this repo with this one: https://github.com/tushar10sh/sveltekit-oidc#readme which sadly was abandoned and no longer runs on latest sveltekit :(

Also, I have no idea how my auth server is implemented, I think it uses keycloak instead of Auth0, can this be another problem for me? Do I need to configure Auth0 differently?

**Comment by markfswe** [comment]
`import orm from '<<sequelize orm project>>'`

As a frontend dev who mainly makes HTML/CSS layouts (yet), this line killed me :D After this I decided to open the issue, because I think, my app doesn't really need it's own DB

**Comment by ChrisOgden** [comment]
> `import orm from '<<sequelize orm project>>'`
> 
> As a frontend dev who mainly makes HTML/CSS layouts (yet), this line killed me :D After this I decided to open the issue, because I think, my app doesn't really need it's own DB

An ORM or database isn't needed, I included it as I was creating the readme from my use case.

**Comment by ChrisOgden** [comment]
> So the question is how can I drop DB from this setup and which features/abilities I'll loose? And maybe you'll understand me if you'll compare readme from this repo with this one: https://github.com/tushar10sh/sveltekit-oidc#readme which sadly was abandoned and no longer runs on latest sveltekit :(

Let me see if I can provide a simplified example based on what is provided in that project. It might not be today but I will try for this week.

**Comment by markfswe** [comment]
> Let me see if I can provide a simplified example based on what is provided in that project. It might not be today but I will try for this week.

Tysm <3 and for your responsiveness

**Comment by markfswe** [comment]
Idk, I think my use case is not really for this repo and your lib. I found [authjs.dev](https://authjs.dev/) which supports sveltekit, keycloak, auth0, oauth2 and all stuff out of the box and "as is": https://authjs.dev/reference/sveltekit

Feel free to close the issue :)

**Comment by ChrisOgden** [comment]
Understood. I was hoping to get time in on your request but clearly haven't. When I was first working on this there were not any sveltekit integrations available so I had to hack together my own. The one you have referenced seems much more mature and document even if they only recently added support for sveltekit.
